Positive\WebsiteBundle\Entity\Concert:
    type: entity
    table: concert
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        date:
            type: datetime
        image:
            type: string
            length: 255
            nullable: true
        location:
            type: string
            length: 255
        address:
            type: string
            length: 255
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
        description:
            type: text
        url:
            type: string
            length: 255